"use client";

/* ============================================================
   상품 주소 칸 — 옛 'URL 슬러그' 를 대신한다.

   왜 바꿨나:
   ① 'URL 슬러그' 는 비개발자가 아는 말이 아니다. 필수(*) 칸인데 무엇을 넣는 곳인지 알 수 없었다.
   ② 한글 상품명을 치면 자동 생성기가 뜻 없는 코드(예: item-0kaheyu1o2vt66)를 박아 넣는다.
      그대로 저장하면 그게 고객이 보는 주소가 되어, 링크를 공유해도 무슨 상품인지 알 수 없고
      나중에 관리자도 못 알아본다. 그렇다고 지우면 필수값 오류로 저장이 막힌다.
   ③ 옛 안내문은 "한글도 됩니다" 라고 말했지만 실제 검증은 영문만 받는다. 한글을 넣으면
      "한글을 쓸 수 있습니다" 라는 거절 메시지가 떠서 빠져나올 방법이 없었다.

   그래서 이 칸은 기본적으로 접혀 있고(자동 생성값을 그대로 쓰면 된다),
   펼쳐야 직접 고칠 수 있으며, 자동 생성값이 뜻 없는 코드로 떨어진 경우에는
   영문 주소를 직접 정하도록 눈에 띄게 권한다.
   ============================================================ */

import { Help, Input } from "@/components/admin/Field";
import { Pencil } from "lucide-react";

export interface ProductAddressFieldProps {
  value: string;
  onChange: (next: string) => void;
  isNew: boolean;
  /**
   * 펼침 여부를 부모가 들고 있는 이유:
   * 저장이 막혔을 때 '상품 주소를 입력해 주세요' 를 누르면 폼이 이 칸의 입력으로 커서를 옮기는데,
   * 접혀 있으면 그 입력 자체가 화면에 없어 아무 일도 일어나지 않았다(폼이 찾다가 그냥 넘어간다).
   * 부모가 커서를 옮기기 전에 먼저 펼쳐 줘야 하므로, 이 상태는 여기 가둘 수 없다.
   */
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /**
   * 비어 있을 때 붉은 경고를 띄울지.
   * 상품명조차 없는 새 폼은 주소가 비어 있는 게 정상이라 겁줄 일이 아니지만,
   * 그 밖에는 저장을 막는 진짜 오류이므로 반드시 보여 준다.
   */
  showEmptyError: boolean;
}

/** 서버(shared.ts)와 같은 규칙 — 영문 소문자·숫자·하이픈만 */
const ADDRESS_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * 자동 생성기가 붙이는 뜻 없는 코드인지.
 * 한글만 남은 이름은 base36 14자 토큰으로 대체되므로(lib/format.ts slugify),
 * 마지막 마디가 숫자를 포함한 14자면 사람이 지은 이름이 아니라고 본다.
 */
function looksAutoGenerated(address: string): boolean {
  return /(?:^|-)(?=[a-z0-9]{14}$)(?=[a-z0-9]*\d)[a-z0-9]{14}$/.test(address);
}

/** 입력한 글자에서 주소로 쓸 수 있는 부분만 남긴 추천값 (남는 게 없으면 null) */
function suggestAddress(raw: string): string | null {
  const folded = raw.normalize("NFKD").toLowerCase().replace(/\p{M}/gu, "");
  const base = folded.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return base || null;
}

export default function ProductAddressField({
  value,
  onChange,
  isNew,
  open,
  onOpenChange,
  showEmptyError,
}: ProductAddressFieldProps) {
  const address = value.trim();
  const empty = address === "";
  const invalid = !empty && !ADDRESS_RE.test(address);
  const autoCode = !empty && !invalid && looksAutoGenerated(address);
  const suggestion = invalid ? suggestAddress(address) : null;
  const badChars = invalid
    ? Array.from(new Set(address.replace(/[a-z0-9-]/g, "").replace(/\s/g, " ").split("")))
        .filter(Boolean)
        .slice(0, 6)
    : [];

  return (
    <div>
      {/* 접힌 상태 — 고객이 보게 될 주소를 읽기만 한다 */}
      <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
        <p className="text-sm text-ink-700">
          {empty ? (
            <span className="text-ink-400">상품명을 넣으면 자동으로 만들어집니다.</span>
          ) : (
            <>
              <span className="text-ink-400">고객이 보게 될 주소 · </span>
              <span className="break-all font-medium">/products/{address}</span>
            </>
          )}
        </p>
        <button
          type="button"
          onClick={() => onOpenChange(!open)}
          className="inline-flex items-center gap-1 border border-ink-200 bg-cream-50 px-3 py-1.5 text-xs text-ink-700 transition-colors hover:border-forest-600 hover:text-forest-700"
        >
          <Pencil size={12} strokeWidth={1.5} />
          {open ? "접기" : "주소 직접 정하기"}
        </button>
      </div>

      {open && (
        <div className="mt-3">
          <Input
            id="p-slug"
            value={value}
            onChange={(e) => onChange(e.target.value)}
            placeholder="예: yeoju-konjac-rice"
            aria-invalid={invalid || undefined}
            className={invalid ? "border-signal-red focus:border-signal-red" : ""}
          />
          <Help>
            영문 소문자·숫자·하이픈(-)만 쓸 수 있습니다. 한글·공백은 쓸 수 없습니다. 상품을 알아볼 수
            있는 영문 이름으로 지어 주시면 고객에게 링크를 보낼 때도, 나중에 찾을 때도 편합니다.
          </Help>
          {!isNew && (
            <Help>
              이미 알려 둔 주소를 바꾸면 예전 링크로 들어온 고객은 이 상품을 찾지 못합니다. 꼭 필요할
              때만 바꿔 주세요.
            </Help>
          )}
        </div>
      )}

      {/* 그대로 두면 사고가 나는 상태들 — 접혀 있어도 항상 보인다 */}
      {empty && showEmptyError && (
        <Help tone="error">상품 주소를 넣어 주세요. 비어 있으면 저장할 수 없습니다.</Help>
      )}

      {invalid && (
        <div className="mt-1.5">
          <p className="text-xs leading-relaxed text-signal-red">
            주소에 쓸 수 없는 글자가 있습니다
            {badChars.length > 0 && <> — {badChars.map((c) => (c === " " ? "빈칸" : c)).join(" ")}</>}.
            영문 소문자·숫자·하이픈(-)만 쓸 수 있습니다.
          </p>
          {suggestion && suggestion !== address ? (
            <button
              type="button"
              onClick={() => {
                onChange(suggestion);
                onOpenChange(true);
              }}
              className="mt-1.5 border border-ink-200 bg-cream-50 px-3 py-1.5 text-xs text-ink-700 transition-colors hover:border-forest-600 hover:text-forest-700"
            >
              /products/{suggestion} 로 바꾸기
            </button>
          ) : (
            <p className="mt-1 text-xs leading-relaxed text-ink-400">
              한글은 주소로 쓸 수 없어 남는 글자가 없습니다. 영문으로 직접 지어 주세요. 예:
              yeoju-konjac-rice
            </p>
          )}
        </div>
      )}

      {autoCode && (
        <p className="mt-1.5 text-xs leading-relaxed text-signal-amber">
          상품명이 한글이라 뜻을 알 수 없는 임시 주소가 자동으로 만들어졌습니다. 이대로 두면 링크를
          받은 고객도, 나중에 보는 관리자도 어떤 상품인지 알 수 없습니다. &lsquo;주소 직접 정하기&rsquo; 를 눌러
          영문 주소를 지어 주세요. (예: yeoju-konjac-rice)
        </p>
      )}
    </div>
  );
}
